name: Deploy to AWS ECS Fargate

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    name: Deploy to AWS ECS Fargate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR file with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          AWS_REGION: us-east-1  # Change to your AWS region
          ECR_REPOSITORY: my-ecr-repo  # Change to your ECR repository name
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update ECS service
        env:
          AWS_REGION: us-east-1
          ECS_CLUSTER: my-ecs-cluster  # Change to your ECS cluster name
          ECS_SERVICE: my-ecs-service  # Change to your ECS service name
          ECS_TASK_DEFINITION: ecs-task-definition.json  # Update as needed
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
